[[formats]]
display_name = "Reference"
[formats.fields]
score = { type = "float" }
text = { type = "str" }

[[formats]]
display_name = "ReferenceWithCriticism"
[formats.fields]
relevant = { type = "bool" }
text = { type = "str" }

[[formats]]
display_name = "Criticism"
[formats.fields]
passages = { type = "List[ReferenceWithCriticism]" }
explanation = { type = "str" }
sufficient = { type = "bool" }

[[formats]]
display_name = "RAGFormat"
[formats.fields]
reference = { type = "List[str]" }
final_answer = { type = "str" }
