[[mcp_tools]]
name = "local_retriever"
type = "stdio"
command = "uv"
args = "run python rag_server.py stdio"
timeout = 60
    [mcp_tools.env]
    OPENAI_BASE_URL = "https://base.url.com"
    OPENAI_API_KEY = "sk-proxy-test"

[[mcp_tools]]
name = "context7_retriever_sse"
type = "sse"
url = "https://mcp.context7.com/sse"
timeout = 60

[[mcp_tools]]
name = "context7_retriever_streamableHTTP"
type = "streamable-http"
url = "https://mcp.context7.com/mcp"
timeout = 60